#!/bin/bash

echo "Building D&D Metric Converter extension..."

# Ensure directories exist
mkdir -p build

# Add header to content.js
echo "// GENERATED FILE - DO NOT EDIT DIRECTLY
// Edit conversion.js and content-base.js instead
// This file is automatically generated by build.sh

" > content.js

# Concatenate files
cat conversion.js >> content.js
echo "" >> content.js
cat content-base.js >> content.js

echo "Build complete! content.js has been generated."
